import os, os.path, shutil
env = Environment( CC = 'g++')
if (env['PLATFORM'] == 'darwin'):
   env.Append(FRAMEWORKS= ['OpenGL','SDL'])
else:
   env.Append(LIBS=["GL", "SDL"])    

env.Library('RepublicEngine',Glob('*.cpp') )
