import os, os.path, shutil
env = Environment( CC = 'g++')
if (env['PLATFORM'] == 'darwin'):
   env.Append(FRAMEWORKS= ['OpenGL','SDL', 'SDL_mixer'])
else:
   env.Append(LIBS=["GL", "SDL", "SDL_mixer"])    

env.Library('RepublicEngine',Glob('*.cpp') )
