all:
	g++ -o game MainFull.cpp CMeshLoader.cpp CShader.cpp CMesh.cpp Enemy.cpp GameObject.cpp InputManager.cpp Player.cpp Camera.cpp Collision.cpp Bullet.cpp Bullets.cpp Map.cpp HUD.cpp -DGL_GLEXT_PROTOTYPES -lglut -lGL -lGLU

run: 
	./game
