import os, os.path, shutil
env = Environment( CC = 'g++', CPPPATH='../../engine', LIBPATH='../../engine' )
if (env['PLATFORM'] == 'darwin'):
   env.Append(FRAMEWORKS= ['OpenGL','SDL'])
else:
   env.Append(LIBS=["GL", "SDL"])    

env.Append(LIBS=["RepublicEngine"]+env['LIBS'])

SConscript('../../engine/SConstruct')
env.Program('modelviewer', ["modelviewer.cpp"])
