import os, os.path, shutil

includes = ['./engine','./game']
env = Environment( CC = 'g++', CPPPATH=includes, LIBPATH=includes )
mainfiles = ['Main.cpp']
if (env['PLATFORM'] == 'darwin'):
   env.Append(FRAMEWORKS= ['OpenGL','SDL', 'Cocoa', 'SDL_mixer'])
   mainfiles+=['SDLMain.m']
else:
   env.Append(LIBS=["GL", "SDL", "SDL_mixer"])

if (env['PLATFORM'] == 'darwin'):
   env.Append(LIBS=["RepublicEngine","RepublicGame"])
else:
   env.Append(LIBS=["RepublicEngine","RepublicGame"]+env['LIBS'])

for subdir in ['engine','game','tools']:
   env.SConscript('%s/SConstruct' % subdir, {'env':env})

env.Program('starrepublic', mainfiles+Glob("./game/*.cpp"))
